# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Riko Method
maintitle: Riko Method School of Piano
email: admissions@rikomethod.com
address: 3363 Glendale Blvd.
city: Los Angeles
state: CA
zipcode: 90039
telephone: 323-486-7185

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
logourl: "images/logo.png"
url: "http://example.com" # the base hostname & protocol for your site

exclude:
  - README.md
  - bower.json


# Build settings
markdown: kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
